polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list/question', views.QuestionsList.as_view(), name='question_list'),
    path('new/question', views.QuestionCreate.as_view(), name='question_create'),
    path('update/question/<int:pk>', views.QuestionUpdate.as_view(), name='question_update'),

    path('new/choice', views.add_choice, name='add_choice'),
    path('remove/choice', views.remove_choice, name='remove_choice'),
]

wg_example/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),

    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return "{}".format(self.question_text)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "{} - {}: {}".format(self.question, self.choice_text, self.votes)

polls/views.py
from django.views.generic import TemplateView, ListView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.http import JsonResponse

from datetime import datetime

from . import models


def add_choice(request):
    qid = request.GET.get('qid')
    choice_text = request.GET.get('choice_text')

    question = models.Question.objects.get(pk=qid)

    choice = models.Choice(question=question, choice_text=choice_text, votes=0)
    choice.save()

    return JsonResponse({})


def remove_choice(request):
    cid = request.GET.get('cid')

    choice = models.Choice.objects.get(pk=cid)
    choice.delete()

    return JsonResponse({})


class IndexView(TemplateView):
    template_name = "polls/index.html"


class QuestionsList(ListView):
    model = models.Question


class QuestionCreate(CreateView):
    model = models.Question
    fields = ["pub_date", "question_text"]
    success_url = reverse_lazy("polls:question_list")

    def get_initial(self):
        return {
            'pub_date': datetime.now()
        }


class QuestionUpdate(UpdateView):
    model = models.Question
    fields = ["pub_date", "question_text"]
    success_url = reverse_lazy("polls:question_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["choices"] = models.Choice.objects.filter(question=self.object)

        return context

wg_example/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "wg_examples/index.html"

polls/templates/polls/base_polls.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<a href="{% url 'index' %}">Home</a> &gt;
<a href="{% url 'polls:index' %}">Polls</a>

<hr />

{% block content %}{% endblock %}

{% block script %}{% endblock %}

</body>
</html>

polls/templates/polls/index.html
{% extends 'polls/base_polls.html' %}

{% block title %}Polls{% endblock %}

{% block content %}
<h1> Questions </h1>
<ul>
    <li><a href="{% url 'polls:question_list' %}" >Questions List</a></li>
    <li><a href="{% url 'polls:question_create' %}" >Create New Question</a></li>
</ul>
{% endblock %}

polls/templates/polls/question_form.html
{% extends "polls/base_polls.html" %}

{% block title %}Create Question{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="post" />
</form>

{% if object %}
<table>
<thead><tr><th>Choice</th><th>Votes</th></tr><th></th></thead>
<tbody>
    <tr><td><input id="choice" type="text" /></td><td><button class="addChoice">Add Question</button></td><td></td></tr>
{% for choice in choices %}
    <tr><td>{{ choice.choice_text }}</td><td>{{ choice.votes }}</td><td><button class="rmChoice" id="rm_{{ choice.id }}">X</button></td></tr>
{% endfor %}
</tbody>
</table>
{% endif %}

{% endblock %}

{% block script %}
<script>
$(document).ready(function() {
    $("button.addChoice").click(function() {
        var choice = $("#choice").val();

        $.ajax({
            url: '{% url 'polls:add_choice' %}',
            data: {
                'qid': {{object.id}},
                'choice_text': choice
            },
            dataType: 'json',
            success: function(data) {
                $("#choice").val("");
                location.reload();
            }
        });
    });

    $("button.rmChoice").click(function() {
        var idx = this.id.indexOf("_");
        var id = this.id.substring(idx+1);

        $.ajax({
            url: '{% url 'polls:remove_choice' %}',
            data: {
                'cid': id
            },
            dataType: 'json',
            success: function(data) {
                location.reload();
            }
        });

    });
});
</script>
{% endblock %}

polls/templates/polls/question_list.html
{% extends "polls/base_polls.html" %}

{% block title %}Question List{% endblock %}

{% block content %}

<button><a href="{% url 'polls:question_create' %}">New Question</a></button>
<table>
    <thead>
    <tr><th>ID</th><th>Question</th><th>Publiction Date</th></tr>
    </thead>
    <tbody>
{% for object in object_list %}
<tr><td><a href="{% url 'polls:question_update' object.id %}" >{{ object.id }}</a></td><td>{{ object.question_text }}</td><td>{{ object.pub_date }}</td></tr>
{% endfor %}
    </tbody>
</table>

{% endblock %}

templates/wg_examples/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Python / Django Working Group</title>
</head>
<body>
<h1>Applications</h1>
<ul>
    <li><a href="{% url 'polls:index' %}">Polls</a></li>
</ul>
</body>
</html>